leftnav:
- identifier: aab65a70-78ec-456b-b294-9ccde95c799d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: c37a2058-372d-4928-94d0-95741083c2cd
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9ce927a9-80f2-4aa6-8322-7ad8db6645c9
  name: 'Unit 1: Linear Differential Equations'
  pageRef: /pages/unit-1-linear-differential-equations
  weight: 30
- identifier: fb967131-1c0c-4bfc-9111-d146241be79e
  name: 'Unit 2: First-Order Differential Equations'
  pageRef: /pages/unit-2-first-order-differential-equations
  weight: 40
- identifier: caec024a-0599-4a8b-8ab2-551737bbc7b5
  name: 'Unit 3: Linear Algebra'
  pageRef: /pages/unit-3-linear-algebra
  weight: 50
- identifier: bbbe9872-c3cd-438c-900f-ca9fa2c52317
  name: 'Unit 4: Impulses, Fourier Series, Partial Differential Equations'
  pageRef: /pages/unit-4-impulses-fourier-series-partial-differential-equations
  weight: 60
- identifier: a914ae70-29a3-4385-b67d-c0cb3a5d4e5e
  name: 'Unit 5: Qualitative Descriptions of Systems'
  pageRef: /pages/unit-5-qualitative-descriptions-of-systems
  weight: 70
- identifier: 6899ac65-aa3c-40ec-9c2a-85b342c5452f
  name: Topic Notes
  pageRef: /pages/topic-notes
  weight: 80
- identifier: 6468cc06-7312-46f0-a4b5-99bae094db8e
  name: Matlab Tutorials
  pageRef: /lists/matlab-tutorial
  weight: 90
- identifier: 3ff30b95-0561-4780-b09e-8e3261c414b6
  name: Problem Sets
  pageRef: /pages/homework
  weight: 100
- identifier: 56c68512-7717-4c53-aa49-689cbf36c478
  name: Quizzes
  pageRef: /pages/quizzes
  weight: 110
